mysqldb:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - main
            # Uncomment if you want to store dfs tables in a separate database:
            #- dfs
        endpoints:
            user:
                default_schema: main
                privileges:
                    main: admin
            # Uncomment if you want to store dfs tables in a separate database:
            #dfs:
            #    default_schema: dfs
            #    privileges:
            #        dfs: admin
rediscache:
    type: 'redis:3.2'
redissession:
    type: 'redis:3.2'
